steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-west1-docker.pkg.dev/${PROJECT_ID}/nps-public-data/nps-public-data',
           '.']
images: ['us-west1-docker.pkg.dev/${PROJECT_ID}/nps-public-data/nps-public-data']